#!/bin/bash -e

LIST="."

if [ -n "$npm_config_staged" ]; then
  LIST=`git diff --cached --name-only | grep -E '\\.(js|json)$'`
fi

FIX=""
if [ -n "$npm_config_fix" ]; then
  FIX="--fix"
fi

if [ "$LIST" ]; then eslint $FIX --config .eslintrc $LIST; fi
