#!/bin/bash -e

export NODE_ENV=test

# --watch option
if [ -n "$npm_config_watch" ]; then WATCH="--watch"; else WATCH=""; fi

# --coverage option
if [ -n "$npm_config_coverage" ]; then RUNNER="nyc mocha"; else RUNNER="mocha"; fi

$RUNNER \
  --check-leaks \
  --bail \
  --grep ${npm_config_grep:-''} \
  --require test/globals.js \
  --globals test \
  --recursive \
  --timeout 60s \
  --inline-diffs \
  $WATCH \
  test ${npm_config_file:-'lib/**/*.test.js'}
